name: CI/CD - Dev

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore
        run: dotnet restore ./ReportCommandAPI.sln

      - name: Build
        run: dotnet build ./ReportCommandAPI.sln --configuration Release --no-restore

  analyse:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT }}

  publish:
    runs-on: ubuntu-latest
    needs: analyse
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Environment Variables
        run: |
          echo "CASSANDRA_KEYSPACE=${{ secrets.CASSANDRA_KEYSPACE }}" >> $GITHUB_ENV
          echo "CASSANDRA_PORT=${{ secrets.CASSANDRA_PORT }}" >> $GITHUB_ENV
          echo "CASSANDRA_CONTACTPOINT=${{ secrets.CASSANDRA_CONTACTPOINT }}" >> $GITHUB_ENV

      - name: Replace Placeholders in appsettings.json
        run: |
          sed -i "s|{CASSANDRA_KEYSPACE}|${CASSANDRA_KEYSPACE}|g" ./ReportCommandAPI/appsettings.json
          sed -i "s|{CASSANDRA_PORT}|${CASSANDRA_PORT}|g" ./ReportCommandAPI/appsettings.json
          sed -i "s|{CASSANDRA_CONTACTPOINT}|${CASSANDRA_CONTACTPOINT}|g" ./ReportCommandAPI/appsettings.json
        
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/reportcommandapi:dev

  scan_docker_image:
    runs-on: ubuntu-latest
    needs: [ publish ]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Log in to the Container registry 📦
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Scan Docker image 🐳
        uses: snyk/actions/docker@master
        id: docker-image-scan
        continue-on-error: true
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/reportcommandapi:dev
          args: --file=Dockerfile --severity-threshold=medium
          sarif: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
