name: CI/CD - Production

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore
        run: dotnet restore ./ReportCommandAPI.sln

      - name: Build
        run: dotnet build ./ReportCommandAPI.sln --configuration Release --no-restore

  analyse:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT }}

  publish:
    runs-on: ubuntu-latest
    needs: analyse
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Environment Variables
        run: |
          echo "CASSANDRA_KEYSPACE=${{ secrets.CASSANDRA_KEYSPACE }}" >> $GITHUB_ENV
          echo "CASSANDRA_CLIENTID=${{ secrets.CASSANDRA_CLIENTID }}" >> $GITHUB_ENV
          echo "CASSANDRA_CLIENTSECRET=${{ secrets.CASSANDRA_CLIENTSECRET }}" >> $GITHUB_ENV
          echo "CASSANDRA_BUNDLE_FILE=${{ secrets.CASSANDRA_BUNDLE_FILE }}" >> $GITHUB_ENV

      - name: Replace Placeholders in appsettings.json
        run: |
          sed -i "s|{CASSANDRA_KEYSPACE}|${CASSANDRA_KEYSPACE}|g" ./ReportCommandAPI/appsettings.json
          sed -i "s|{CASSANDRA_CLIENTID}|${CASSANDRA_CLIENTID}|g" ./ReportCommandAPI/appsettings.json
          sed -i "s|{CASSANDRA_CLIENTSECRET}|${CASSANDRA_CLIENTSECRET}|g" ./ReportCommandAPI/appsettings.json
          sed -i "s|{CASSANDRA_BUNDLE_FILE}|${CASSANDRA_BUNDLE_FILE}|g" ./ReportCommandAPI/appsettings.json
        
      - name: Download Database Bundle from Azure Storage
        run: |
          az storage blob download -c ${{ secrets.AZURE_STORAGE_CONTAINER }} -n secure-connect-reportcommanddb.zip --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} --account-key ${{ secrets.AZURE_STORAGE_SECRET }} -f ~/downloaded-files

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/reportcommandapi:latest

  scan_docker_image:
    runs-on: ubuntu-latest
    needs: [ publish ]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Log in to the Container registry 📦
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Scan Docker image 🐳
        uses: snyk/actions/docker@master
        id: docker-image-scan
        continue-on-error: true
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/reportcommandapi:latest
          args: --file=Dockerfile --severity-threshold=medium
          sarif: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
